package com.olacabs.customer;

/* renamed from: com.olacabs.customer.a */
public final class R {

    /* renamed from: com.olacabs.customer.a.a */
    public static final class R {
        public static final int[] CardView;
        public static final int CardView_cardBackgroundColor = 0;
        public static final int CardView_cardCornerRadius = 1;
        public static final int CardView_cardElevation = 2;
        public static final int CardView_cardMaxElevation = 3;
        public static final int CardView_cardPreventCornerOverlap = 5;
        public static final int CardView_cardUseCompatPadding = 4;
        public static final int CardView_contentPadding = 6;
        public static final int CardView_contentPaddingBottom = 10;
        public static final int CardView_contentPaddingLeft = 7;
        public static final int CardView_contentPaddingRight = 8;
        public static final int CardView_contentPaddingTop = 9;
        public static final int[] FloatLabelLayout;
        public static final int FloatLabelLayout_floatLabelHint = 5;
        public static final int FloatLabelLayout_floatLabelPaddingBottom = 4;
        public static final int FloatLabelLayout_floatLabelPaddingLeft = 1;
        public static final int FloatLabelLayout_floatLabelPaddingRight = 2;
        public static final int FloatLabelLayout_floatLabelPaddingTop = 3;
        public static final int FloatLabelLayout_floatLabelTextAppearance = 0;
        public static final int[] FontButton;
        public static final int FontButton_font = 0;
        public static final int[] FontEditText;
        public static final int FontEditText_font = 0;
        public static final int[] FontRadioButtont;
        public static final int FontRadioButtont_font = 0;
        public static final int[] FontTextView;
        public static final int FontTextView_font = 0;
        public static final int[] LoadingImageView;
        public static final int LoadingImageView_circleCrop = 2;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 0;
        public static final int[] MapAttrs;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_liteMode = 6;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 15;
        public static final int MapAttrs_uiRotateGestures = 8;
        public static final int MapAttrs_uiScrollGestures = 9;
        public static final int MapAttrs_uiTiltGestures = 10;
        public static final int MapAttrs_uiZoomControls = 11;
        public static final int MapAttrs_uiZoomGestures = 12;
        public static final int MapAttrs_useViewLifecycle = 13;
        public static final int MapAttrs_zOrderOnTop = 14;
        public static final int[] MapM4bAttrs;
        public static final int MapM4bAttrs_m4b_cameraBearing = 1;
        public static final int MapM4bAttrs_m4b_cameraTargetLat = 2;
        public static final int MapM4bAttrs_m4b_cameraTargetLng = 3;
        public static final int MapM4bAttrs_m4b_cameraTilt = 4;
        public static final int MapM4bAttrs_m4b_cameraZoom = 5;
        public static final int MapM4bAttrs_m4b_liteMode = 6;
        public static final int MapM4bAttrs_m4b_mapType = 0;
        public static final int MapM4bAttrs_m4b_uiCompass = 7;
        public static final int MapM4bAttrs_m4b_uiMapToolbar = 15;
        public static final int MapM4bAttrs_m4b_uiRotateGestures = 8;
        public static final int MapM4bAttrs_m4b_uiScrollGestures = 9;
        public static final int MapM4bAttrs_m4b_uiTiltGestures = 10;
        public static final int MapM4bAttrs_m4b_uiZoomControls = 11;
        public static final int MapM4bAttrs_m4b_uiZoomGestures = 12;
        public static final int MapM4bAttrs_m4b_useViewLifecycle = 13;
        public static final int MapM4bAttrs_m4b_zOrderOnTop = 14;
        public static final int[] PasswordStrengthIndicator;
        public static final int PasswordStrengthIndicator_lineWidth = 3;
        public static final int PasswordStrengthIndicator_mediumColor = 2;
        public static final int PasswordStrengthIndicator_poorColor = 1;
        public static final int PasswordStrengthIndicator_strongColor = 0;
        public static final int[] SlidingUpPanelLayout;
        public static final int SlidingUpPanelLayout_umanoAnchorPoint = 8;
        public static final int SlidingUpPanelLayout_umanoClipPanel = 7;
        public static final int SlidingUpPanelLayout_umanoDragView = 5;
        public static final int SlidingUpPanelLayout_umanoFadeColor = 3;
        public static final int SlidingUpPanelLayout_umanoFlingVelocity = 4;
        public static final int SlidingUpPanelLayout_umanoInitialState = 9;
        public static final int SlidingUpPanelLayout_umanoOverlay = 6;
        public static final int SlidingUpPanelLayout_umanoPanelHeight = 0;
        public static final int SlidingUpPanelLayout_umanoParalaxOffset = 2;
        public static final int SlidingUpPanelLayout_umanoShadowHeight = 1;
        public static final int[] com_facebook_like_view;
        public static final int com_facebook_like_view_auxiliary_view_position = 4;
        public static final int com_facebook_like_view_foreground_color = 0;
        public static final int com_facebook_like_view_horizontal_alignment = 5;
        public static final int com_facebook_like_view_object_id = 1;
        public static final int com_facebook_like_view_object_type = 2;
        public static final int com_facebook_like_view_style = 3;
        public static final int[] com_facebook_login_view;
        public static final int com_facebook_login_view_confirm_logout = 0;
        public static final int com_facebook_login_view_login_text = 1;
        public static final int com_facebook_login_view_logout_text = 2;
        public static final int[] com_facebook_profile_picture_view;
        public static final int com_facebook_profile_picture_view_is_cropped = 1;
        public static final int com_facebook_profile_picture_view_preset_size = 0;

        static {
            CardView = new int[]{R.attr.cardBackgroundColor, R.attr.cardCornerRadius, R.attr.cardElevation, R.attr.cardMaxElevation, R.attr.cardUseCompatPadding, R.attr.cardPreventCornerOverlap, R.attr.contentPadding, R.attr.contentPaddingLeft, R.attr.contentPaddingRight, R.attr.contentPaddingTop, R.attr.contentPaddingBottom};
            FloatLabelLayout = new int[]{R.attr.floatLabelTextAppearance, R.attr.floatLabelPaddingLeft, R.attr.floatLabelPaddingRight, R.attr.floatLabelPaddingTop, R.attr.floatLabelPaddingBottom, R.attr.floatLabelHint};
            int[] iArr = new int[com_facebook_profile_picture_view_is_cropped];
            iArr[com_facebook_login_view_confirm_logout] = R.attr.font;
            FontButton = iArr;
            iArr = new int[com_facebook_profile_picture_view_is_cropped];
            iArr[com_facebook_login_view_confirm_logout] = R.attr.font;
            FontEditText = iArr;
            iArr = new int[com_facebook_profile_picture_view_is_cropped];
            iArr[com_facebook_login_view_confirm_logout] = R.attr.font;
            FontRadioButtont = iArr;
            iArr = new int[com_facebook_profile_picture_view_is_cropped];
            iArr[com_facebook_login_view_confirm_logout] = R.attr.font;
            FontTextView = iArr;
            LoadingImageView = new int[]{R.attr.imageAspectRatioAdjust, R.attr.imageAspectRatio, R.attr.circleCrop};
            MapAttrs = new int[]{R.attr.mapType, R.attr.cameraBearing, R.attr.cameraTargetLat, R.attr.cameraTargetLng, R.attr.cameraTilt, R.attr.cameraZoom, R.attr.liteMode, R.attr.uiCompass, R.attr.uiRotateGestures, R.attr.uiScrollGestures, R.attr.uiTiltGestures, R.attr.uiZoomControls, R.attr.uiZoomGestures, R.attr.useViewLifecycle, R.attr.zOrderOnTop, R.attr.uiMapToolbar};
            MapM4bAttrs = new int[]{R.attr.m4b_mapType, R.attr.m4b_cameraBearing, R.attr.m4b_cameraTargetLat, R.attr.m4b_cameraTargetLng, R.attr.m4b_cameraTilt, R.attr.m4b_cameraZoom, R.attr.m4b_liteMode, R.attr.m4b_uiCompass, R.attr.m4b_uiRotateGestures, R.attr.m4b_uiScrollGestures, R.attr.m4b_uiTiltGestures, R.attr.m4b_uiZoomControls, R.attr.m4b_uiZoomGestures, R.attr.m4b_useViewLifecycle, R.attr.m4b_zOrderOnTop, R.attr.m4b_uiMapToolbar};
            PasswordStrengthIndicator = new int[]{R.attr.strongColor, R.attr.poorColor, R.attr.mediumColor, R.attr.lineWidth};
            SlidingUpPanelLayout = new int[]{R.attr.umanoPanelHeight, R.attr.umanoShadowHeight, R.attr.umanoParalaxOffset, R.attr.umanoFadeColor, R.attr.umanoFlingVelocity, R.attr.umanoDragView, R.attr.umanoOverlay, R.attr.umanoClipPanel, R.attr.umanoAnchorPoint, R.attr.umanoInitialState};
            com_facebook_like_view = new int[]{R.attr.foreground_color, R.attr.object_id, R.attr.object_type, R.attr.style, R.attr.auxiliary_view_position, R.attr.horizontal_alignment};
            com_facebook_login_view = new int[]{R.attr.confirm_logout, R.attr.login_text, R.attr.logout_text};
            com_facebook_profile_picture_view = new int[]{R.attr.preset_size, R.attr.is_cropped};
        }
    }
}
